### Program 1
Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
def vander(x, N, order):
    X = x.size
    result_array = np.empty((N + 1, X), dtype = int)
    
    if order.upper() == "TRUE":
        for i in range(N + 1):
            power_vector = np.array(np.power(x, i))
            result_array[i] = power_vector
    else:
        for i in range(N-1, -1, -1):
            power_vector = np.array(np.power(x, i))
            result_array[(N-1)-i] = power_vector
    return result_array

In [2]:
import numpy as np

N = int(input('Enter the value of N power :'))

print('Enter comma separated list of elements eg. 1,2,3 :')
input_vector = input()
input_list = list(map(int, input_vector.split(',')))
x = np.array(input_list)
print('Input vector is :')
print(x)

order = input("Enter 'True' for increasing order of powers else enter 'False' :")

result_array = vander(x,N,order)
print('The final matrix is :')
print(result_array.T)

Enter the value of N power :3
Enter comma separated list of elements eg. 1,2,3 :
1,2,3
Input vector is :
[1 2 3]
Enter 'True' for increasing order of powers else enter 'False' :True
The final matrix is :
[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]]


### Program 2
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [3]:
import numpy as np
dataset = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

def movingaverage(values,window):
    weights = np.repeat(1.0,window)/window
    smas = np.convolve(values,weights,'valid')
    return smas 


movingaverage(dataset,3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])